### ISSUE TITLE
Yii2 Support?

### ISSUE THREAD

**Issue by Sammaye** [phpnode/YiiSolr#12]
Are you considering Yii2 support for this extension?

Yii2 has no Solr extension and it seems as though this is the strongest one.

**Comment by phpnode** [comment]
@Sammaye I'm not, because I'm no longer using Solr myself, switched to ElasticSearch instead. This repo might form a good starting point for someone else who'd like to do so though.

**Comment by Sammaye** [comment]
Ok kool thanks
