### ISSUE TITLE
Parent: child process exited with status 255 

### ISSUE THREAD

**Issue by utkarshpanwar** [phpnode/YiiSolr#2]
Getting Parent: child process exited with status 255, in some case where I write query syntax like this LAST_NAME:panwar

Here is sample code i am trying which is crashing Apache

$criteria = new ASolrCriteria;
$criteria->query = "LAST_NAME:panwar"; // lucene query syntax
$docs = PartnerSolrDocument::model()->findAll($criteria);

Same query syntax works fine if I use the solr admin interface http://localhost:8983/solr/select?q=LAST_NAME:panwar 

Where could be the issue, please let me know if you can put some light on this issue.

Also if you can provide some samples for faceted search that would be great.

Thanks!

**Comment by phpnode** [comment]
Can you turn on the profiling log route and paste the query that is being sent to solr, the line should start with: packages.solr.AConnection.rawSearch

Also do other YiiSolr functions work like inserting / updating? (i.e. are the connection details specified correctly)

**Comment by phpnode** [comment]
Some to think of it, this is an apache out of memory issue, if you're returning a lot of rows with your search this could be why. Use ASolrDataProvider with pagination to limit the number of results, or add $criteria->limit = 10; to your current code

**Comment by utkarshpanwar** [comment]
There is just one record that I want to fetch using my search criteria. There is no out of memory issue. Apache just crashes with this message: Parent: child process exited with status 255 

Here is the trace:
2011/11/24 10:39:21 [trace] [packages.solr.ASolrConnection] Querying Solr: q=LAST_NAME:panwar

Other things like Inserting/Updating of YiiSolr working fine.

Just to let you know I am using wamp on Win7.

I noticed one thing like in my schema.xml I have added following line:



 <defaultSearchField>FIRST_NAME</defaultSearchField>

So I use the query with default search field then it works fine but If I use others field then Apache crashes, something weird.

// This works fine
$criteria->query = "FIRST_NAME:panwar"; 

// This query crashes Apache
$criteria->query = "LAST_NAME:panwar"; 

Using solr search interface, everything works fine
http://localhost:8983/solr/select?q=LAST_NAME:panwar

**Comment by utkarshpanwar** [comment]
In solr console (command prompt window where solr server is running using "java -jar start.jar" command), I can see requests are coming from the Yii app and hits is also 1 or 2. but still Apache crashing.

INFO: [] webapp=/solr path=/select/ params={indent=on&wt=xml&q=LAST_NAME:panwar&version=2.2} hits=1 status=0 QTime=0

**Comment by phpnode** [comment]
ok please try this:

<pre>
$solrClient = PartnerSolrDocument::model()->getSolrConnection()->getClient();
$criteria = new SolrQuery;
$criteria->setQuery("LAST_NAME:panwar");
print_r($solrClient->query($criteria)->getResponse());
</pre>


crash or no crash?

**Comment by phpnode** [comment]
also i merged some commits just now, please make sure you have the latest copy of the code

**Comment by utkarshpanwar** [comment]
I got the latest code.

Still same issue, Apache crashes with this code too

$solrClient = PartnerSolrDocument::model()->getSolrConnection()->getClient();
$criteria = new SolrQuery;
$criteria->setQuery("LAST_NAME:panwar");
print_r($solrClient->query($criteria)->getResponse());

Above code works fine if I use the query FIRST_NAME:panwar, in this case I get no results:

SolrObject Object ( [responseHeader] => SolrObject Object ( [status] => 0 [QTime] => 0 [params] => SolrObject Object ( [indent] => on [wt] => xml [q] => FIRST_NAME:panwar [version] => 2.2 ) ) [response] => SolrObject Object ( [numFound] => 0 [start] => 0 [docs] => ) ) 

I was wrong in my previous message like query with FIRST_NAME  (which is default search field schema in schema.xml) always work fine, in some case like FIRST_NAME:abhinav  apache still crashes.

Here is the result of this search using solr interface. 

Do you thing something is wrong with results, which is causing Apache crash?

http://localhost:8983/solr/select?q=FIRST_NAME:abhinav
&lt;response&gt;
  &lt;lst name="responseHeader"&gt;
    &lt;int name="status"&gt;0&lt;/int&gt;
    &lt;int name="QTime"&gt;0&lt;/int&gt;
    &lt;lst name="params"&gt;
      &lt;str name="q"&gt;FIRST_NAME:abhinav&lt;/str&gt;
    &lt;/lst&gt;
  &lt;/lst&gt;
  &lt;result name="response" numFound="1" start="0"&gt;
    &lt;doc&gt;
      &lt;str name="BODY_TYPE"&gt;Athletic&lt;/str&gt;
      &lt;str name="CHILDREN_STATUS"&gt;No&lt;/str&gt;
      &lt;str name="CITY"&gt;Agoura Hills&lt;/str&gt;
      &lt;str name="COUNTRY"&gt;USA&lt;/str&gt;
      &lt;date name="DOB"&gt;1995-11-08T00:00:00Z&lt;/date&gt;
      &lt;str name="DRINKING"&gt;Yes, regularly&lt;/str&gt;
      &lt;str name="EDUCATION"&gt;Masters Degree&lt;/str&gt;
      &lt;str name="EMAIL_ADDRESS"&gt;abhi@mailinator.com&lt;/str&gt;
      &lt;str name="ETHNICITY"&gt;Latino/Hispanic&lt;/str&gt;
      &lt;str name="FAVORITE_ACTIVITES"&gt;activies&lt;/str&gt;
      &lt;str name="FAVORITE_BOOKS"&gt;books&lt;/str&gt;
      &lt;str name="FAVORITE_GAMES"&gt;games&lt;/str&gt;
      &lt;str name="FAVORITE_MUSIC"&gt;music&lt;/str&gt;
      &lt;str name="FAVORITE_SPORTS"&gt;sports&lt;/str&gt;
      &lt;str name="FAVORITE_TV_SHOWS"&gt;shows&lt;/str&gt;
      &lt;str name="FIRST_DATE"&gt;ideal first&lt;/str&gt;
      &lt;str name="FIRST_NAME"&gt;abhinav&lt;/str&gt;
      &lt;str name="HEIGHT_FEET"&gt;4 feet&lt;/str&gt;
      &lt;str name="HEIGHT_INCH"&gt;6 inch&lt;/str&gt;
      &lt;str name="HOBBIES"&gt;hobbies&lt;/str&gt;
      &lt;str name="INTERESTED_IN"&gt;Women&lt;/str&gt;
      &lt;str name="LAST_NAME"&gt;saxena&lt;/str&gt;
      &lt;str name="MARRIED_STATUS"&gt;Widowed&lt;/str&gt;
      &lt;str name="PERFECT_MATCH"&gt;perfect&lt;/str&gt;
      &lt;str name="PHOTO"/&gt;
      &lt;str name="RELATION_INTERESTED_IN"&gt;Marriage&lt;/str&gt;
      &lt;str name="RELIGION"&gt;Spiritual&lt;/str&gt;
      &lt;str name="SCREEN_NAME"&gt;abhi&lt;/str&gt;
      &lt;str name="SEX"&gt;m&lt;/str&gt;
      &lt;str name="SMOKING"&gt;Yes, regularly&lt;/str&gt;
      &lt;str name="STATE"&gt;CALIFORNIA&lt;/str&gt;
      &lt;str name="STORY"&gt;my story&lt;/str&gt;
      &lt;str name="USER_ID"&gt;5d0ff759-b7ea-6381-f783-f957890b0828&lt;/str&gt;
    &lt;/doc&gt;
  &lt;/result&gt;
&lt;/response&gt;

**Comment by phpnode** [comment]
This looks like a bug with the solr pecl extension, not YiiSolr itself. Please file a bug report with pecl for this issue.
