### ISSUE TITLE
Issue with ASolrDataProvider

### ISSUE THREAD

**Issue by utkarshpanwar** [phpnode/YiiSolr#3]
The code below works fine

<pre>
$criteria=new ASolrCriteria;
$criteria->addCondition("screen_name:hari*");
$criteria->addCondition("sex:m");
$docs = PartnerSolrDocument::model()->findAll($criteria);
</pre>

Here is the query submitted to solr, message displayed in the solr console as below:-

<pre>
INFO: [] webapp=/solr path=/select/ params={indent=on&wt=xml&q=(screen_name:hari*)+AND+(sex:m)&version=2.2} hits=1 status=0 QTime=1
</pre>

But if I use the code below:

<pre>
$criteria=new ASolrCriteria;
$criteria->addCondition("screen_name:hari*");
$criteria->addCondition("sex:m");
$p =  new ASolrDataProvider('PartnerSolrDocument', array('criteria'=>$criteria,));
var_dump($p->getData());
</pre>

I get the following error;

<pre>
java.lang.NumberFormatException: For input string: "0q=(screen_name:hari*) AND (sex:m)"
at java.lang.NumberFormatException.forInputString(Unknown Source)
</pre>

Here is the query being submitted to solr:

<pre>
INFO: [] webapp=/solr path=/select/ params={indent=on&start=0&q=(screen_name:har
i*)+AND+(sex:m)&wt=xml&version=2.2&rows=0q%3D(screen_name:hari*)+AND+(sex:m)&row
s=10} status=500 QTime=2
</pre>

Here q is coming two times and that even without & before that.

But if write the code as below, although it works but query being submitted is wrong

<pre>
$criteria=new ASolrCriteria;
$criteria->addCondition("screen_name:hari*");
$criteria->addCondition("sex:m");

$criteria->setStart(0);
$criteria->setLimit(13);
             
$p =  new ASolrDataProvider('PartnerSolrDocument', array('criteria'=>$criteria,));
                
var_dump($p->getData());
</pre>

Outout on solr console, some field are also duplicated. Why rows=10 is coming with rows=13?

<pre>
INFO: [] webapp=/solr path=/select/ params={indent=on&start=0&start=0&start=0&q=
(screen_name:hari*)+AND+(sex:m)&wt=xml&version=2.2&rows=13&rows=0q%3D(screen_nam
e:hari*)+AND+(sex:m)&rows=13&rows=10} hits=1 status=0 QTime=1
</pre>

**Comment by phpnode** [comment]
This looks like a bug with ASolrCriteria::mergeWith(), i will investigate, just to confirm this should work:

<pre>
$p =  new ASolrDataProvider('PartnerSolrDocument');
$p->criteria->query = "screen_name:hari* AND sex:m";
var_dump($p->getData());
</pre>


if that doesn't work, try:

<pre>
$p =  new ASolrDataProvider('PartnerSolrDocument');
$p->criteria->addFilterQuery("screen_name:hari* AND sex:m");
var_dump($p->getData());
</pre>

**Comment by utkarshpanwar** [comment]
In first case below , I got the error "Property "ASolrDataProvider.query" is not defined"

In second case, I got the error 'ASolrDataProvider and its behaviors do not have a method or closure named "addFilterQuery".'

-----Original Message-----

**Comment by phpnode** [comment]
oops, i made a typo, please see my updated comment.

**Comment by utkarshpanwar** [comment]
Those statements works fine but still multiple times fields are added in the query, not just 'rows' field other fields too.

For example, if code below is executed, then fields like fq, d, queryOpts rows, start etc are added multiple times:

$criteria->addCondition("sex:". $interestedIn);
$criteria->addCondition("state:".$this->city);  
$criteria->setParam('fq', '{!bbox}');
$criteria->setParam('d', $d);
$criteria->setParam('sfield', 'latlong');
$criteria->setParam('pt', $this->latlong);
$criteria->setParam('queryOpts', 'spatial');
$criteria->addInCondition("education", $this->education);

**Comment by phpnode** [comment]
please can you post the solr query string (from the profiling logs) that the above code generates?

**Comment by utkarshpanwar** [comment]
Here it is:-

<pre>
2011/11/30 06:52:11 [trace] [packages.solr.ASolrConnection] Counting Results from Solr: q=(sex:f) AND (dob:[NOW-50YEAR TO NOW-18YEAR])&rows=12&rows=0&fq={!bbox}&d=48.27&sfield=latlong&pt=45.6387281,-122.6614861&queryOpts=spatial
in C:\wamp\www\hoojook\protected\packages\solr\ASolrConnection.php (175)
in C:\wamp\www\hoojook\protected\packages\solr\ASolrDocument.php (641)
in C:\wamp\www\hoojook\protected\packages\solr\ASolrDataProvider.php (98)
2011/11/30 06:52:11 [profile] [application] begin:packages.solr.AConnection.rawSearch(q=(sex:f) AND (dob:[NOW-50YEAR TO NOW-18YEAR])&rows=12&rows=0&fq={!bbox}&d=48.27&sfield=latlong&pt=45.6387281,-122.6614861&queryOpts=spatial)
2011/11/30 06:52:12 [profile] [application] end:packages.solr.AConnection.rawSearch(q=(sex:f) AND (dob:[NOW-50YEAR TO NOW-18YEAR])&rows=12&rows=0&fq={!bbox}&d=48.27&sfield=latlong&pt=45.6387281,-122.6614861&queryOpts=spatial)
</pre>

**Comment by phpnode** [comment]
This is definitely a problem with criteria merging, which is annoying because i was sure this was fixed now. i will see what i can do,

**Comment by mwzhang** [comment]
I guess it may relate to the working mechanism of Solr connections.

Hereby I tentatively propose a way to fix it. However, it is just a probing attempt, which hopefully will lead to better solution from others.

Step 1:

Add the following function to ASolrConnection.php:

```
public function resetClient() {
    $this->_client = new SolrClient($this->getClientOptions()->toArray());
}
```

Step2:

Add a line 

```
    $this->model->getSolrConnection()->resetClient();
```

to somewhere around line 85 in ASolrDataProvider.php just before the line:

```
    $data=$this->model->findAll($criteria);
```

So that it looks like:

```
    $this->model->getSolrConnection()->resetClient();
    $data=$this->model->findAll($criteria);
```

Now everything should work and I guess you can figure out what is previously wrong. Good luck!

**Comment by phpnode** [comment]
Closing this issue because it's old and since I can't replicate this locally I'm not sure how to proceed. If you are still having problems please reply here and I'll reopen the issue and take a closer look.
